baseurl = "https://pabes.me/"
title = "Patrick Abraham"
author = "Patrick Abraham"
canonifyurls = true
languagecode = "en"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
hasCJKLanguage = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs"

[params]
pagetitle = "Patrick Abraham"
copyright = "Â© 2021 Patrick Abraham"
copyrightUrl = "https://pabes.me/"
faviconfile = "image/favicon.png"
logofile = "image/avatar.jpg"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "pjabes"
twitter = "pjabes"
linkedin = "pjabes"
email = "example@example.com"

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2

[[menu.primary]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 3